services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainspaghetti-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=brainspaghetti
    volumes:
      - ./backend:/usr/src/app
    command: pnpm run start:dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - brainspaghetti-net

  db:
    image: mysql:8.0
    container_name: brainspaghetti-db
    restart: always
    environment:
      MYSQL_DATABASE: brainspaghetti
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - brainspaghetti-net

volumes:
  db-data:

networks:
  brainspaghetti-net:
